### ISSUE TITLE
KnowledgeGraphForge.sparql(query, rewrite=False) rewrites LIMIT

### ISSUE THREAD

**Issue by joni-herttuainen** [BlueBrain/nexus-forge#262]
__Issue__
When doing a `sparql(..., rewrite=False)` call, the `LIMIT` written in the query string is not reinforced, it needs to be manually fed as a keyword argument. Is this the expected behavior?

I would have expected that `rewrite=False` would guarantee the query string is not manipulated.

This seems to affect at least the latest release and the current version in master.

__Repro__
```python
query = 
"""
# PREFIXES
SELECT ?id WHERE {
    ?id a nsg:DetailedCircuit
} LIMIT 1
"""
forge.sparql(query, debug=True, rewrite=False)
```
Debug output:
```
PREFIXES
SELECT ?id WHERE {
    ?id a nsg:DetailedCircuit
} LIMIT 100
```
To get what I expected:
```python
query = 
"""
# PREFIXES
SELECT ?id WHERE {
    ?id a nsg:DetailedCircuit
}
"""
forge.sparql(query, debug=True, rewrite=False, limit=1)
```

**Comment by crisely09** [comment]
I have a possible (and straightforward) solution: keep the query **as given** when `rewrite=False`, specifically the `limit` and `offset` parameters, and print a warning if any of these parameters is passed to the method, announcing they won't be taken into account because `rewrite` was set to `False`.

**Comment by crisely09** [comment]
Also, it would be good to not have any limit, and just use what is given in the query, or even have an option to not have a limit.
