### ISSUE TITLE
Context does not resolve NCBITaxon terms.

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/nexus-forge#386]
Resolving an `NCBITaxon` term using forge's context:
```python
c = forge.get_model_context()
c.resolve("NCBITaxon:10000")
```
Returns:
```
'ncbitaxon:10000'
```
Failing to resolve the prefix.

In contrast when an mba term is resolved it works as expected:
```python
resolved = c.resolve("mba:997")
assert resolved == 'http://api.brain-map.org/api/v2/data/Structure/997'
```
The `NCBITaxon` term is present in the context's document:
```python
c.document["@context"]["NCBITaxon"]
# 'http://purl.obolibrary.org/obo/NCBITaxon_'
```
Checking how the `mba` and `NCBITaxon` terms are stored in the context:
```
Term(id='http://purl.obolibrary.org/obo/NCBITaxon_', name='NCBITaxon', type=0, container=set(), index=None, language=0, reverse=False, context=0, prefix=False, protected=False)
Term(id='http://api.brain-map.org/api/v2/data/Structure/', name='mba', type=0, container=set(), index=None, language=0, reverse=False, context=0, prefix=True, protected=False)
```
There is a difference in the `prefix` boolean, which is False in the `NCBITaxon` case. That leads to not replacing it in this line:
https://github.com/RDFLib/rdflib/blob/6563ea0a4ced5b3c858fe143bf3360cc1c1eb711/rdflib/plugins/shared/jsonld/context.py#L356

Most of the times this is not an issue for forge because it merges the source of a resource with the metadata and iin most cases the id in the source is expanded. However, in a resource where the term is also collapsed in the source, then the resolution fails:
```python
r = forge.retrieve("https://bbp.epfl.ch/data/bbp/mmb-point-neuron-framework-model/9a107d17-3b9c-4bf6-a68a-c822ffa79c75")
r.subject.species
# Resource(_last_action=None, _validated=False, _synchronized=True, _store_metadata=None, id='ncbitaxon:10090', label='Mus musculus', _inner_sync=True)
```

**Comment by eleftherioszisis** [comment]
The `NCBITaxon` is not recognized as a prefix because of this:
https://github.com/RDFLib/rdflib/blob/6563ea0a4ced5b3c858fe143bf3360cc1c1eb711/rdflib/plugins/shared/jsonld/context.py#L236-L237
where the valid URI endings are:
https://github.com/RDFLib/rdflib/blob/6563ea0a4ced5b3c858fe143bf3360cc1c1eb711/rdflib/plugins/shared/jsonld/context.py#L68

**Comment by MFSY** [comment]
Hi @eleftherioszisis,

We are aware of this. As you pointed, NCBITaxon maps to "http://purl.obolibrary.org/obo/NCBITaxon_" and the ending of this URL makes rdflib not expand it to the corresponding URI. 

- Now, NCBITaxon:10090 with `NCBITaxon == http://purl.obolibrary.org/obo/NCBITaxon_` leads to perfectly valid URI (http://purl.obolibrary.org/obo/NCBITaxon_10090) as far as RDF is concerned. The data gets in the Triple store and is queryable. The situation here is more about jsonld than rdf.

- CURIEs like NCBITaxon:10090 are also used in Bioportal as well: https://bioportal.bioontology.org/ontologies/FOODON/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_10090&jump_to_nav=true. NCBITaxon seems to be valid prefix used out there.

> r = forge.retrieve("https://bbp.epfl.ch/data/bbp/mmb-point-neuron-framework-model/9a107d17-3b9c-4bf6-a68a-c822ffa79c75")
r.subject.species # Resource(_last_action=None, _validated=False, _synchronized=True, _store_metadata=None, id='ncbitaxon:10090', label='Mus musculus', _inner_sync=True)

- We recommend to not use curies (like NCBITaxon:10090) in ids. So that clients don't feel the need to expand using a context. If you provide a fully expanded URI (http://purl.obolibrary.org/obo/NCBITaxon_10090), you'll get it back fully expanded when you run forge.retrieve().

That said, I understand the need to be able to expand to full URI any curies you might get  our KG and that's fair. Let me know if you have a different use case in mind.

Two options here to enable this:

- We remove NCBITaxon in the context and use the obo prefix (which is already there in the context). That means http://purl.obolibrary.org/obo/NCBITaxon_10090 could be shorten as obo:NCBITaxon_10090. That means all data with curie like NCBITaxon:* to be migrated to fully expanded id
- Or we override resolve, expand methods of rdflib jsonld in [kgforge.core.commons.context.Context](https://github.com/BlueBrain/nexus-forge/blob/master/kgforge/core/commons/context.py) to deal with this case. 

I prefer the second option.

**Comment by eleftherioszisis** [comment]
> Or we override resolve, expand methods of rdflib jsonld in [kgforge.core.commons.context.Context](https://github.com/BlueBrain/nexus-forge/blob/master/kgforge/core/commons/context.py) to deal with this case.

I prefer the second option too. However, you could also use monkeypatching to avoid overriding the methods and let the rdflib Context use its own functionality:
```python
from rdflib.plugins.shared.jsonld import context
URI_GEN_DELIMS = context.URI_GEN_DELIMS + ("_",)
```
and then patch the `URI_GEN_DELIMS ` constant when initializing the context here:
https://github.com/BlueBrain/nexus-forge/blob/413856ab2ea39734e79a11585363e18a1ab4a896/kgforge/core/commons/context.py#L38
Like this:
``` python
    with patch("rdflib.plugins.shared.jsonld.context.URI_GEN_DELIMS", URI_GEN_DELIMS):
        super().__init__(document) 
```
which in principle should force the rdflib context to consider the "_" ending terms as prefixes. That way you shouldn't need to change anything else, but needs to be tested.

**Comment by MFSY** [comment]
Hi @eleftherioszisis ,

Reading https://github.com/RDFLib/rdflib/issues/2606, it turns out:

- others have the same issue
- @prefix could be added in the jsonld context to signal a prefix but that required using jsonld 1.1
- No need for overriding or monkeypatching
I made an [PR](https://github.com/BlueBrain/nexus-forge/pull/387) to bump jsonld from 1.0 (default) to 1.1. 
I've also made an [MR](https://bbpgitlab.epfl.ch/dke/apps/brain-modeling-ontology/-/merge_requests/229) to change our json ld context.

**Comment by eleftherioszisis** [comment]
Nice, this is even better. 

Are there other tools that would also need to use jsonld 1.1 to resolve the context? I don't know how the nexus side of things works.

**Comment by MFSY** [comment]
Yeah, Nexus Delta should probably move to jsonld 1.1 if that is not the case yet. Pinging @imsdu
